{% set name = "rapifilt" %}
{% set version = "1.0" %}
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/andvides/RAPIFILT/releases/download/v1.0/RAPIFILT_v1.zip
  sha256: 2400da5807c6647760a6b4fb92f3a1aa38896d200e61d685711308d6f6c08bc5
  
build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - htslib 
    - boost
    - boost-cpp
    - libboost

test:
  commands:
    - rapifilt -h 2>&1 | grep "rapifilt" > /dev/null

about:
  home: https://github.com/andvides/RAPIFILT.git
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: "RAPIFILT:RAPId FILTer is a quality control of DNA sequences"
