{% set name = "rapifilt" %}
{% set version = "1.0" %}
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> 31c21b3150d55e5d7d16cf9426cf9f6e1adcdd48
=======

>>>>>>> b96a0aaf440bbb39cbcf4b9f0712fbe49d425cdf
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
<<<<<<< HEAD
<<<<<<< HEAD
  url: https://github.com/andvides/RAPIFILT/releases/download/v1.0/RAPIFILT_v1.zip
=======
  url: https://github.com/andvides/RAPIFILT/releases/download/v{{ version}}/RAPIFILT_v1.zip
>>>>>>> 31c21b3150d55e5d7d16cf9426cf9f6e1adcdd48
=======
  url: https://github.com/andvides/RAPIFILT/releases/download/v{{ version}}/RAPIFILT_v1.zip
>>>>>>> b96a0aaf440bbb39cbcf4b9f0712fbe49d425cdf
  sha256: f25f93c278bbbed666351c403e37ee49d67399b0b490adb90546e325c198da3f
  
build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
<<<<<<< HEAD
<<<<<<< HEAD
    - htslib 
    - boost
=======
    - boost-cpp
  run:
>>>>>>> 31c21b3150d55e5d7d16cf9426cf9f6e1adcdd48
=======
    - boost-cpp
  run:
>>>>>>> b96a0aaf440bbb39cbcf4b9f0712fbe49d425cdf
    - boost-cpp

test:
  commands:
    - rapifilt -h 2>&1 | grep "rapifilt" > /dev/null

about:
  home: https://github.com/andvides/RAPIFILT.git
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: "RAPIFILT:RAPId FILTer is a quality control of DNA sequences"
