{% set name = "rapifilt" %}
{% set version = "1.0" %}
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/andvides/RAPIFILT/releases/download/v1.0/RAPIFILT_v1.zip
  sha256: f25f93c278bbbed666351c403e37ee49d67399b0b490adb90546e325c198da3f
  
build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - htslib 
    - boost
    - boost-cpp
    - libboost > 1.65

test:
  commands:
    - rapifilt -h 2>&1 | grep "rapifilt" > /dev/null

about:
  home: https://github.com/andvides/RAPIFILT.git
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: "RAPIFILT:RAPId FILTer is a quality control of DNA sequences"
