{% set name = "selectfasta" %}
{% set version = "1.0" %}
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/andvides/selectFasta/tarball/v1.0
  md5: 14accc2112305a3667b4d9e8e33b2912
  
build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}

about:
	home: https://github.com/andvides/selectFasta/
  license: GNU
  summary: "FASTA or FASTQ select from a list of header names"
