{% set version = "2.0.4" %}

package:
  name: biasaway
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/b/biasaway/biasaway-{{ version }}.tar.gz
  sha256: "f850dcf4f19259d360939c4c4f64370ca7247bbeaa069c166a2ef6354d4f4858"

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - biopython
    - numpy <=1.16.5

test:
  imports:
    - biasaway
  commands:
    - biasaway --help

about:
  home: https://bitbucket.org/CBGR/biasaway
  license: GPLv3
  license_family: GPL
  summary: "BiasAway: a tool to generate composition-matched background sequences"
  description: "BiasAway provides user with six models for generating background sequences useful to enrichment analyses. These backgrounds derived from mono- and di- nucleotide shuffled sequences, and genomic sequences matched to the GC content of the target data."
  doc_url: 'https://biasaway.rtfd.io'

extra:
  recipe-maintainers:
    - asntech
